### ISSUE TITLE
About the specifications of KRaft

### ISSUE THREAD

**Issue by AlphaCanisMajoris** [Vanlightly/raft-tlaplus#1]
Hi! I'm a researcher that is currently learning the KRaft protocol and implementation. The specifications in this repo really help a lot. I find it interesting to develop multiple levels of specifications for KRaft (see the directory [pull-raft](https://github.com/Vanlightly/raft-tlaplus/tree/main/specifications/pull-raft): [PullRaft.tla](https://github.com/Vanlightly/raft-tlaplus/blob/main/specifications/pull-raft/PullRaft.tla), [KRaft.tla](https://github.com/Vanlightly/raft-tlaplus/blob/main/specifications/pull-raft/KRaft.tla) & [KRaftWithReconfig.tla](https://github.com/Vanlightly/raft-tlaplus/blob/main/specifications/pull-raft/KRaftWithReconfig.tla).

In my understanding, PullRaft.tla is more like a protocol specification that describes the core protocol design of a pull-based Raft variant. In contrast, KRaft.tla is specified based on the Kafka KRaft implementation, and KRaftWithReconfig.tla is developed based on KRaft.tla with the feature of reconfiguration.  The latter two stay more close to the implementation, so they can be used to verify the correctness of the code implementation with higher conformance. 

I wonder if my above understanding is right. Thanks!

**Comment by Vanlightly** [comment]
Yes that is correct. However, I have now written a better specification over in my kafka-tlaplus repo. There is one for reconfiguration that is faithful to the reconfiguration KIP-853. https://github.com/Vanlightly/kafka-tlaplus/tree/main/kraft/kip_853

Also, I have implemented a specification for the data replication protocol, which interacts with Kraft controllers. Included is a prose description of the protocol along with it. https://github.com/Vanlightly/kafka-tlaplus/tree/main/kafka_data_replication/kraft

Those would be good places to go to learn about KRaft and how it interacts with the partition replication protocol.

**Comment by AlphaCanisMajoris** [comment]
That really helps a lot! Thanks for your reply!
